version: 0.2

phases:
  pre_build:
    commands:
      - cd EatMeUp-Client
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: EatMeUp-Client/build
